---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sc
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-sc
  hostPath:
    path: /tmp/pv-sc-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      labels:
        app: data-exchange-sc
    spec:
      containers:
      - name: writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - >
            while true; do
              echo "$(date)" >> /data/shared.txt;
              sleep 5;
            done
        volumeMounts:
        - name: shared-sc
          mountPath: /data
      - name: reader
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - "tail -f /data/shared.txt"
        volumeMounts:
        - name: shared-sc
          mountPath: /data
      volumes:
      - name: shared-sc
        persistentVolumeClaim:
          claimName: pvc-sc
